### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by pehbehbeh** [curiosum-dev/kanta#43]
First things first: Thank you very much for this great package! We are currently in the process of integrating it into a new project. In the process, we noticed a small but significant bug:

When changing the page via the pagination nothing is happening on the page. There is no error logged and you can see a successfull LiveView response - just no changes for the table view.

I think I've found out why that is: In `KantaWeb.Translations.TranslationsLive.handle_params/3` the `params["page"] || "1"` is passed as a string... and in `Kanta.Query.paginate/3` you have this line:

```
page = if is_number(page), do: max(page, 1), else: 1
```

So you are always stuck on page `1`?

When changing [this line](https://github.com/curiosum-dev/kanta/blob/beb4a16c61e4b34c47a3e573168a102ee951a8a4/lib/kanta_web/live/translations/translations_live/translations_live.ex#L32) to the following everything works as expected:

```elixir
        |> Keyword.merge(page: String.to_integer(params["page"] || "1"))
```

But I'm a little unsure: there is no such problem in the demo. Has the bug already been fixed elsewhere?

**Comment by ravensiris** [comment]
I've submitted a fix.
You can try it out before it get's released like this:
```elixir
# mix.exs
defp deps do
      # ...
      {:kanta, github: "curiosum-dev/kanta", override: true, branch: "bugfix/pagination-conversion"}
end
```

**Comment by pehbehbeh** [comment]
Thanks for the quick fix. The pagination is working again!

Even if there is no option in the UI yet, I believe that `per_page` has the same problem.

**Comment by pehbehbeh** [comment]
Just noticed: The domain filter is not working (anymore?) in the `bugfix/pagination-conversion` branch.
