### ISSUE TITLE
Kanta duplicates kanta_message records when context is null

### ISSUE THREAD

**Issue by kubosuke** [curiosum-dev/kanta#65]
# Environment

- fly.io
- Elixir 1.17
- Postgres 14
- po files:

```
❯ find . -name "default.po"
./priv/gettext/nl/LC_MESSAGES/default.po
./priv/gettext/en/LC_MESSAGES/default.po
```

# Overview

in our application, Kanta duplicates Message records and it causes unexpected behaviour.

<img width="1459" alt="image" src="https://github.com/curiosum-dev/kanta/assets/40480197/b2d39c46-0bac-432a-a792-dd44ebfd7b76">

as we investigate the behaviour, we found that unique constraint is defined at here:

https://github.com/curiosum-dev/kanta/blob/4df9af25e9e476b370ce60b972896bd258ddde95/lib/kanta/migrations/postgresql/v01.ex#L111

but it didn't work properly, because we don't define any context, and contexts are registered as `null` in the database.
ref: https://stackoverflow.com/a/8289253

How about forcing users to define context, or set default context if it's not defined?

**Comment by ravensiris** [comment]
@kubosuke 
Hi, got assigned to this issue. 
Seems like you've made a PR but closed it.
Was there a reason for closing?
Did it not solve your issue?

**Comment by kubosuke** [comment]
@ravensiris 
Hi thanks for your reply.

Yeah once I thought by applying default context we could resolve this issue like this:
https://github.com/curiosum-dev/kanta/pull/66/files

but finally we decided to apply additional UNIQUE constraint to `:domain_id, :msgid` cause it's easier and it doesn't require to modify current kanta codes. but it'd be nice if we can apply default context if it's missing.
