### ISSUE TITLE
command to invalidate cache

### ISSUE THREAD

**Issue by kubosuke** [curiosum-dev/kanta#72]
# Environment:

- fly.io
- Elixir 

```
Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]
IEx 1.17.2 (compiled with Erlang/OTP 26)
```

# Overview

We're deploying 3 app instances on fly.io, and sometimes when I update translate text on Kanta, some app instance holds cache and the translate text won't be updated immediately. it'd be nice if kanta has the logic to [invalidate cache](https://hexdocs.pm/nebulex/Nebulex.Cache.html#c:delete_all/2) manually (like `invalidate cache` button in GUI, etc). fetch data from database periodically to refresh is also fine.

**Comment by jan-swiatek** [comment]
Added! :)

**Comment by kubosuke** [comment]
@jan-swiatek  love ie thanks 🙇
