### ISSUE TITLE
Style corruption in v0.4.1 ?

### ISSUE THREAD

**Issue by kubosuke** [curiosum-dev/kanta#91]
I got this style corruption error when I pull the latest kanta ( https://github.com/curiosum-dev/kanta/releases/tag/0.4.1 )

<img width="972" alt="image" src="https://github.com/user-attachments/assets/d6716f2c-7bf1-4bba-bac9-27afc091287e">
<img width="776" alt="image" src="https://github.com/user-attachments/assets/fc0a6059-bbea-436b-8c2c-73010fe94ca8">

**Comment by kubosuke** [comment]
as far as I tested on https://github.com/curiosum-dev/kanta/releases/tag/0.4.0 it's fine
<img width="1894" alt="image" src="https://github.com/user-attachments/assets/12334898-0e60-4b0c-a33b-a8d27b22bdc2">
<img width="1868" alt="image" src="https://github.com/user-attachments/assets/5a4b93b6-aff6-4195-836c-0295621a7760">

**Comment by kubosuke** [comment]
FYI

```
❯ iex -v
Erlang/OTP 26 [erts-14.2.5.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

IEx 1.17.1 (compiled with Erlang/OTP 26)
```

**Comment by peaceful-james** [comment]
I have this same problem. It is fixed by simply running `mix assets.build` in the source code. I made a PR:

https://github.com/curiosum-dev/kanta/pull/94

In the meantime you can make your kanta work by changing the dep in your `mix.exs` to this:

```
      {:kanta, git: "https://github.com/peaceful-james/kanta", branch: "fix-broken-tailwind-css", override: true},
```

**Comment by peaceful-james** [comment]
@kubosuke Can this issue be closed?
